apiVersion: v2
name: cilium-aks-config
description: A Helm Chart to create Cilium Config for Azure CNI chaining.
type: application
version: 0.0.1
appVersion: 0.0.1
maintainers:
  - name: Saeid Bostandoust
    email: ssbostan@yahoo.com
